### ISSUE TITLE
Create a predefined object for every book of the Bible

### ISSUE THREAD

**Issue by gideontong** [gideontong/biblepoet#15]

**Comment by nathansit** [comment]
Does this go in index.ts?

**Comment by gideontong** [comment]
> Does this go in index.ts?

Nope

**Comment by nathansit** [comment]
bro what do you mean nope

**Comment by gideontong** [comment]
It should go in its own folder

**Comment by nathansit** [comment]
<img width="428" alt="image" src="https://github.com/gideontong/biblepoet/assets/25888434/972571d7-bdf6-4f9a-9230-e16a04b1d0af">

Is this right or are each of the object going to be in it's own file

**Comment by gideontong** [comment]
You're close. Why don't you open a PR and we can discuss this?
